import type { Metadata } from "next";
import { cookies } from "next/headers";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { APP_LOCALE_COOKIE, resolveLocale } from "@/features/settings/locale";
import { resolveTheme, THEME_COOKIE } from "@/features/settings/theme";
// Self-hosted (plan §27's "zero network dependency" — next/font/google
// requires reaching fonts.googleapis.com at build/dev time, which the rest
// of this offline-capable platform never does). @fontsource ships the
// actual woff2 files inside the package; --font-plex-sans/--font-plex-mono
// are defined in globals.css, not generated by next/font.
import "@fontsource/ibm-plex-sans/latin-400.css";
import "@fontsource/ibm-plex-sans/latin-500.css";
import "@fontsource/ibm-plex-sans/latin-600.css";
import "@fontsource/ibm-plex-sans/latin-700.css";
import "@fontsource/ibm-plex-mono/latin-400.css";
import "@fontsource/ibm-plex-mono/latin-500.css";
import "@fontsource/ibm-plex-mono/latin-600.css";
import "@fontsource/ibm-plex-mono/latin-700.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Interview Platform",
  description: "Universal, JD-driven interview assessment platform.",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const cookieStore = await cookies();
  const theme = resolveTheme(cookieStore.get(THEME_COOKIE)?.value);
  const locale = resolveLocale(cookieStore.get(APP_LOCALE_COOKIE)?.value);

  return (
    <html lang={locale} className={`h-full antialiased ${theme === "dark" ? "dark" : ""}`}>
      <body className="flex min-h-full">
        <AppSidebar locale={locale} />
        <div className="flex min-w-0 flex-1 flex-col">{children}</div>
      </body>
    </html>
  );
}
